#!/bin/sh
# vim: ft=tcl
# the next line restarts using expect \
    LC_TYPE=C exec expect -f "$0" -- "$@"

array set ::opt {
    verbose 0
    ref_sample_number 1024
    sdmsh ../../sdmsh
}

remove_nulls -d 0
remove_nulls 0
log_user 1

# NOTE: problems with binary data in stdin/stdout
#   * fconfigure help only for stdin (?)
#   * >>>>> 'send_*' and 'interact' corrupt binary data, use puts -nonewline <<<<<
#
fconfigure stdin  -translation binary -buffering none
fconfigure stdout -translation binary -buffering none

# need to prevent internal encoding conversion
encoding system iso8859-1

#stty raw -echo

match_max 2000
set timeout -1

############## start: help function ######################
array set c {
    none  "\033\[0m"    white "\033\[1;37m"
    red   "\033\[0;31m" lred  "\033\[1;31m"
    grn   "\033\[0;32m" lgrn  "\033\[1;32m"
    yel   "\033\[0;33m" lyel  "\033\[1;33m"
    mag   "\033\[0;35m" lmag  "\033\[1;35m"
    lblue "\033\[1;36m" cyan  "\033\[0;36m"
}

proc die {msg} {
    upvar c c
    puts stderr "die: $c(lred)$msg$c(none)"
    exit 1
}

proc fail {msg} {
    upvar c c
    puts -nonewline " $c(lred)fail:\n$msg$c(none)"
    flush stdout
}

proc warn {msg} {
    upvar c c
    puts -nonewline $c(yel)$msg$c(none)
    flush stdout
}

proc ok {} {
    upvar c c
    puts " $c(lgrn) ok$c(none)"
}

#proc msg {msg} {
#    upvar c c
#    puts -nonewline $c(cyan)$msg$c(none)
#    flush stdout
#}
# TODO: loglevel
proc msg {type msg} {
    upvar c c
    switch $type {
        fail    {set col $c(lred)}
        warn    {set col $c(lmag)}
        note    {set col $c(lyel)}
        info    {set col $c(cyan)}
        dbg     {set col $c(lmag)}
        norm    {set col {}}
        stage   {
            set col $c(yel)
            set msg "\n====== $msg ======\n"
        }
        default {set col {}}
    }
    puts -nonewline $col$msg$c(none)
    flush stdout
}

proc hexdump string {
    binary scan $string H* hex
    regexp -all -inline .. $hex
}

proc beep {} {
    after 0 {
        send_tty "\x07"
        for {set i 0} {$i < 5} {incr i} {
            sleep 1
            send_tty "\x07"
        }
    }
}

proc rand {min max} {
    return [expr {int(rand() * ($max - $min + 1) + $min)}]
}

proc check_for_following {type} {
    global argv0
    if {![llength [uplevel set argv]]} {
        send_error "$argv0: [uplevel set flag] requires following $type"
        exit 2
    }
}

############## end: help function ######################

proc show_help_and_die {} {
    global argv0 image_types
    send_error "Usage: [regsub .*/ $argv0 {}] \[-h|--help] \[-v] \[-s ref_sample_number] \[--] ip script.sdmsh\n\
    -s  - referece samples number for referense less then 1024 samples.\n\
    \n\
    -h  - this help\n\
    -v  - verbose output\n\
    "
    exit 1
}

while { [llength $argv] > 0 } {
    set flag [lindex $argv 0]
    if {0 == [regexp "^-" $flag]} break
    set argv [lrange $argv 1 end]
    switch -- $flag {
        -s    {
            set ::opt(ref_sample_number) [lindex $argv 0]
            check_for_following number
            set argv [lrange $argv 1 end]
        }
        -v    { set opt(verbose) 1 }
        -h -
        --help { show_help_and_die }
        --    { incr i; break }
        ^-    { die "unknown option: \"$flag\"" }
    }
}

set argv [string trim $argv \{\}]
set argc [llength $argv]

if {$argc != 2} {
    show_help_and_die
}

set ip   [lindex $argv 0]
set type [lindex $argv 1]

switch $ip {
    [0-9.]* {}
    * { die "first parameter must be IP or host number" }
}

switch $type {
    active - passive {}
    * { die "secondt parameter must be 'active' or 'passive'" }
}

spawn $::opt(sdmsh) $ip -sf usbl-range-$type.sdmsh

set stage 0
expect -re {tx_time = (\d+), rx_time = (\d+)[^\d]} {
    if {$type == "active"} {
        switch $stage {
            0 { set start $expect_out(1,string) }
            1 { set end   [expr $expect_out(2,string) - $::opt(ref_sample_number) * 16] }
        }
    } else {
        switch $stage {
            0 { set start [expr $expect_out(2,string) - $::opt(ref_sample_number) * 16] }
            1 { set end   $expect_out(1,string) }
        }
    }
    incr stage
    exp_continue
} timeout {
    exp_continue
} eof {
}

if {![info exist start] || ![info exist end]} {
    catch wait reason
    if {![info exist reason]} {
        die fail\n
    }

    set rc [lindex $reason 3]
    if {$rc == 42} {
        die "Modem not in SDM mode. Please run command: echo +++ATP | nc 192.168.0.[regexp -inline {\d+$} $ip] 9200"
    } elseif {$rc == 43} {
        die "Modem in BUSY mode. Try switch to normal mode ++ATA and then back to SDM mode ++ATP"
    }
    die fail
}

if {$end < $start} {
    msg warn "fix overflow\n"
    set end [expr $end + (0xffffffff - $start)]
    set start 0
}

set delta [expr $end - $start]
msg info "$type delta: $delta\n"

